name: Update GraalVM

on:
  schedule:
    - cron: 0 15 * * 1-5
  workflow_dispatch:

jobs:
  run:
    name: "Run Java Migration for GraalVM"
    strategy:
      fail-fast: false
      matrix:
        java-version: [ 17, 21, 25 ]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Java 24
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: 24
          cache: 'maven'
      - name: Run graalvm
        run: ./mvnw spring-boot:run -Dspring-boot.run.arguments="--foojay.java.distribution=graalvm --foojay.distribution.version=${{ matrix.java-version }} --foojay.java.release-status=ga"
        env:
          SDKMAN_RELEASE_CONSUMER_KEY: ${{ secrets.CONSUMER_KEY }}
          SDKMAN_RELEASE_CONSUMER_TOKEN: ${{ secrets.CONSUMER_TOKEN }}
