name: Update OpenJDK EA

on:
  schedule:
    - cron: 0 15 * * 1-5
  workflow_dispatch:

jobs:
  run:
    name: "Run Java Migration for OpenJDK EA"
    strategy:
      fail-fast: false
      matrix:
        java-version: [ 26 ]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Java 25
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: 25
          cache: 'maven'
      - name: Run oracle
        run: ./mvnw spring-boot:run -Dspring-boot.run.arguments="--foojay.java.distribution=oracle_open_jdk --foojay.distribution.version=${{ matrix.java-version }} --foojay.java.release-status=ea"
        env:
          SDKMAN_RELEASE_CONSUMER_KEY: ${{ secrets.CONSUMER_KEY }}
          SDKMAN_RELEASE_CONSUMER_TOKEN: ${{ secrets.CONSUMER_TOKEN }}
