name: Update FX BellSoft Liberica

on:
  schedule:
    - cron: 0 15 * * 1-5
  workflow_dispatch:

jobs:
  run:
    name: "Run Java Migration for BellSoft Liberica"
    strategy:
      fail-fast: false
      matrix:
        java-version: [ 8, 11, 17, 21, 25 ]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Java 24
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: 24
          cache: 'maven'
      - name: Run bellsoft-liberica
        run: ./mvnw spring-boot:run -Dspring-boot.run.arguments="--foojay.java.distribution=liberica --foojay.distribution.version=${{ matrix.java-version }} --foojay.java.release-status=ga --foojay.java.javafx-bundled=true"
        env:
          SDKMAN_RELEASE_CONSUMER_KEY: ${{ secrets.CONSUMER_KEY }}
          SDKMAN_RELEASE_CONSUMER_TOKEN: ${{ secrets.CONSUMER_TOKEN }}
